# Generated by Django 4.2 on 2023-04-29 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(default='', max_length=50)),
                ('name_en', models.CharField(default='', max_length=50)),
                ('name_th_sh', models.CharField(default='', max_length=30)),
                ('name_en_sh', models.CharField(default='', max_length=30)),
                ('level', models.CharField(default='', max_length=30)),
                ('studyTime', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(default='', max_length=50)),
                ('name_en', models.CharField(default='', max_length=50)),
                ('name_sh', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Facculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(default='', max_length=50)),
                ('name_en', models.CharField(default='', max_length=50)),
                ('university', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='')),
                ('telephone', models.CharField(default='', max_length=20)),
                ('website', models.CharField(default='', max_length=50)),
                ('vision', models.TextField(default='')),
                ('slogan', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=30, unique=True)),
                ('s_id', models.CharField(default='', max_length=15)),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='อาจารย์', max_length=15)),
                ('gender', models.TextField(default='ชาย', max_length=15)),
                ('address', models.TextField(default='')),
                ('birthDate', models.DateField(default=None)),
                ('hiringDate', models.DateField(default=None)),
                ('picture', models.ImageField(default='', upload_to='static/images/personnels/')),
                ('division', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.division')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='อาจารย์ประจำหลักสูตร', max_length=30)),
                ('curriculum', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.curriculumn')),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default=None, max_length=100)),
                ('detail', models.TextField(default=None)),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='', max_length=30)),
                ('degree_th', models.CharField(default='', max_length=50)),
                ('degree_en', models.CharField(default='', max_length=50)),
                ('degree_th_sh', models.CharField(default='', max_length=30)),
                ('degree_en_sh', models.CharField(default='', max_length=30)),
                ('yearGraduate', models.ImageField(default=0, upload_to='')),
                ('institute', models.CharField(default='', max_length=50)),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docType', models.CharField(default=None, max_length=15)),
                ('refId', models.IntegerField(default=0)),
                ('fileName', models.CharField(default=None, max_length=100)),
                ('fileType', models.CharField(default=None, max_length=30)),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.personnel')),
            ],
        ),
        migrations.AddField(
            model_name='curriculumn',
            name='division',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.division'),
        ),
    ]
