# Generated by Django 4.2 on 2023-05-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(default='', max_length=50)),
                ('name_en', models.CharField(default='', max_length=50)),
                ('name_sh', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(default='', max_length=100)),
                ('name_en', models.CharField(default='', max_length=100)),
                ('university', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='')),
                ('telephone', models.CharField(default='', max_length=20)),
                ('website', models.CharField(default='', max_length=50)),
                ('vision', models.TextField(default='')),
                ('philosophy', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=30, unique=True)),
                ('sId', models.CharField(default='', max_length=15)),
                ('firstname_th', models.CharField(default='', max_length=50)),
                ('lastname_th', models.CharField(default='', max_length=50)),
                ('firstname_en', models.CharField(default='', max_length=50)),
                ('lastname_en', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='อาจารย์', max_length=30)),
                ('type', models.CharField(default='สายวิชาการ', max_length=30)),
                ('gender', models.CharField(default='ชาย', max_length=15)),
                ('address', models.TextField(default='')),
                ('birthDate', models.DateField(default=None)),
                ('hiringDate', models.DateField(default=None)),
                ('picture', models.ImageField(default=None, upload_to='static/images/personnels/')),
                ('division', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.division')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default=None, max_length=100)),
                ('detail', models.TextField(default=None)),
                ('experience', models.TextField(default=None)),
                ('recordDate', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PersonnelExpertise', to='baseapp.personnel')),
                ('recorder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderExpertise', to='baseapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='', max_length=30)),
                ('degree_th', models.CharField(default='', max_length=100)),
                ('degree_en', models.CharField(default='', max_length=100)),
                ('degree_th_sh', models.CharField(default='', max_length=50)),
                ('degree_en_sh', models.CharField(default='', max_length=50)),
                ('yearGraduate', models.IntegerField(default=0)),
                ('institute', models.CharField(default='', max_length=100)),
                ('recordDate', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PersonnelEducation', to='baseapp.personnel')),
                ('recorder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderEducation', to='baseapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(default=None, max_length=15)),
                ('refId', models.IntegerField(default=0)),
                ('filename', models.CharField(default=None, max_length=100)),
                ('filetype', models.CharField(default=None, max_length=30)),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(default=None, upload_to='static/documents/')),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(default='', max_length=100)),
                ('name_en', models.CharField(default='', max_length=100)),
                ('name_th_sh', models.CharField(default='', max_length=50)),
                ('name_en_sh', models.CharField(default='', max_length=50)),
                ('level', models.CharField(default='', max_length=30)),
                ('studyTime', models.IntegerField(default=4)),
                ('division', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.division')),
            ],
        ),
        migrations.CreateModel(
            name='CurrAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='อาจารย์ประจำหลักสูตร', max_length=30)),
                ('recordDate', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.curriculum')),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PersonnelCurrAffiliation', to='baseapp.personnel')),
                ('recorder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderCurrAffiliation', to='baseapp.personnel')),
            ],
        ),
    ]
