# Generated by Django 4.2 on 2023-07-06 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='currently',
            field=models.CharField(default='ปฏิบัติหน้าที่ปกติ', max_length=50),
        ),
        migrations.AddField(
            model_name='personnel',
            name='telephone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='type',
            field=models.CharField(default='ข้าราชการ(สายวิชาการ)', max_length=50),
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getDate', models.DateTimeField(default=None)),
                ('level', models.CharField(default='ชั้นที่ 5', max_length=15)),
                ('name', models.CharField(default='', max_length=100)),
                ('name_sh', models.CharField(default='', max_length=30)),
                ('type', models.CharField(default='ต่ำกว่าสายสะพาย', max_length=30)),
                ('recordDate', models.DateTimeField(auto_now_add=True)),
                ('editDate', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='EditorDecoration', to='baseapp.personnel')),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PersonnelDecoration', to='baseapp.personnel')),
                ('recorder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderDecoration', to='baseapp.personnel')),
            ],
        ),
    ]
