# Generated by Django 4.2 on 2023-05-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curraffiliation',
            name='editDate',
        ),
        migrations.RemoveField(
            model_name='curraffiliation',
            name='editor',
        ),
        migrations.AlterField(
            model_name='personnel',
            name='editorId',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='recorderId',
            field=models.IntegerField(default=None),
        ),
    ]
