# Generated by Django 4.2 on 2023-05-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='type',
            field=models.CharField(default='สายวิชาการ', max_length=10),
        ),
    ]
