# Generated by Django 4.2 on 2023-04-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facculty',
            new_name='Faculty',
        ),
        migrations.AddField(
            model_name='documents',
            name='file',
            field=models.FileField(default=None, upload_to='static/documents/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='picture',
            field=models.ImageField(default=None, upload_to='static/images/personnels/'),
        ),
    ]
