# Generated by Django 4.2 on 2023-05-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['firstname_th', 'lastname_th', 'status']},
        ),
    ]
