# Generated by Django 4.2 on 2023-05-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_alter_personnel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='type',
            field=models.CharField(default='สายวิชาการ', max_length=30),
        ),
    ]
