# Generated by Django 4.2 on 2023-05-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_remove_curraffiliation_editdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
