# Generated by Django 4.2 on 2023-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_personnel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='curriculumYear',
            field=models.IntegerField(default=0),
        ),
    ]
