# Generated by Django 4.2 on 2023-05-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_personnel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.division')),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PersonnelResponsible', to='baseapp.personnel')),
                ('recorder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderResponsible', to='baseapp.personnel')),
            ],
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
