# Generated by Django 4.2 on 2023-06-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_responsible_delete_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=None, max_length=50)),
                ('recordDate', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PersonnelManager', to='baseapp.personnel')),
                ('recorder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderManager', to='baseapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.division')),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PersonnelHeader', to='baseapp.personnel')),
                ('recorder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderHeader', to='baseapp.personnel')),
            ],
        ),
    ]
