# Generated by Django 4.2 on 2023-05-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_curriculum_curriculumyear'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
