# Generated by Django 4.2 on 2023-05-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comId', models.CharField(default='', max_length=30)),
                ('comDate', models.DateField(default=None)),
                ('fiscalYear', models.IntegerField(default=0)),
                ('eduYear', models.IntegerField(default=0)),
                ('eduSemeter', models.CharField(default='', max_length=10)),
                ('mission', models.CharField(default='การจัดการเรียนการสอน', max_length=50)),
                ('topic', models.TextField(default=None)),
                ('detail', models.TextField(default=None)),
                ('recordDate', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderCommand', to='baseapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default=None)),
                ('endDate', models.DateField(default=None)),
                ('days', models.IntegerField(default=1)),
                ('fiscalYear', models.IntegerField(default=0)),
                ('eduYear', models.IntegerField(default=0)),
                ('leaveType', models.CharField(default=None, max_length=50)),
                ('reason', models.CharField(default=None, max_length=255)),
                ('recordDate', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PersonnelLeave', to='baseapp.personnel')),
                ('recorder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderLeave', to='baseapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getDate', models.DateField(default=None)),
                ('fiscalYear', models.IntegerField(default=0)),
                ('eduYear', models.IntegerField(default=0)),
                ('eduSemeter', models.IntegerField(default=0)),
                ('topic', models.CharField(default=None, max_length=255)),
                ('detail', models.TextField(default=None)),
                ('budget', models.FloatField(default=0.0)),
                ('budgetType', models.CharField(default='งบประมาณรายได้', max_length=30)),
                ('source', models.CharField(default='', max_length=255)),
                ('recordDate', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PersonnelPerformance', to='baseapp.personnel')),
                ('recorder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderPerformance', to='baseapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscalYear', models.IntegerField(default=0)),
                ('title_th', models.TextField(default='')),
                ('title_en', models.TextField(default='')),
                ('objective', models.TextField(default='')),
                ('percent_resp', models.IntegerField(default=100)),
                ('budget', models.FloatField(default=0.0)),
                ('budgetType', models.CharField(default='งบประมาณรายได้', max_length=30)),
                ('source', models.CharField(default='', max_length=255)),
                ('keyword', models.TextField(default='')),
                ('percent_success', models.IntegerField(default=0)),
                ('publish_method', models.TextField(default='')),
                ('recordDate', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderResearch', to='baseapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='SocialService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default=None)),
                ('endDate', models.DateField(default=None)),
                ('days', models.IntegerField(default=1)),
                ('fiscalYear', models.IntegerField(default=0)),
                ('eduYear', models.IntegerField(default=0)),
                ('eduSemeter', models.IntegerField(default=0)),
                ('topic', models.FloatField(default=0.0)),
                ('objective', models.TextField(default='')),
                ('place', models.CharField(default='', max_length=255)),
                ('budget', models.FloatField(default=0.0)),
                ('budgetType', models.CharField(default='งบประมาณรายได้', max_length=30)),
                ('source', models.CharField(default='', max_length=255)),
                ('receiver', models.CharField(default='', max_length=255)),
                ('num_receiver', models.IntegerField(default=0)),
                ('recordDate', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderSocialService', to='baseapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default=None)),
                ('endDate', models.DateField(default=None)),
                ('days', models.IntegerField(default=1)),
                ('fiscalYear', models.IntegerField(default=0)),
                ('eduYear', models.IntegerField(default=0)),
                ('eduSemeter', models.IntegerField(default=0)),
                ('topic', models.CharField(default=None, max_length=255)),
                ('place', models.CharField(default=None, max_length=255)),
                ('budget', models.FloatField(default=0.0)),
                ('budgetType', models.CharField(default='งบประมาณรายได้', max_length=30)),
                ('recordDate', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PersonnelTraining', to='baseapp.personnel')),
                ('recorder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderTraining', to='baseapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default=None, max_length=255)),
                ('training', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='static/documents/leave')),
                ('filetype', models.CharField(default=None, max_length=50)),
                ('training', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.training')),
            ],
        ),
        migrations.CreateModel(
            name='SocialServiceURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default=None, max_length=255)),
                ('socialservice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.socialservice')),
            ],
        ),
        migrations.CreateModel(
            name='SocialServicePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=30)),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.personnel')),
                ('socialservice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.socialservice')),
            ],
        ),
        migrations.CreateModel(
            name='SocialServiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='static/documents/socialservice')),
                ('filetype', models.CharField(default=None, max_length=50)),
                ('socialservice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.socialservice')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default=None, max_length=255)),
                ('research', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.research')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=30)),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.personnel')),
                ('research', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.research')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='static/documents/research')),
                ('filetype', models.CharField(default=None, max_length=50)),
                ('research', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.research')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default=None, max_length=255)),
                ('performance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.performance')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='static/documents/performance')),
                ('filetype', models.CharField(default=None, max_length=50)),
                ('performance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.performance')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default=None, max_length=255)),
                ('leave', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.leave')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='static/documents/leave')),
                ('filetype', models.CharField(default=None, max_length=50)),
                ('leave', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.leave')),
            ],
        ),
        migrations.CreateModel(
            name='CommandURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default=None, max_length=255)),
                ('command', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.command')),
            ],
        ),
        migrations.CreateModel(
            name='CommandPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=30)),
                ('command', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.command')),
                ('personnel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='CommandFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='static/documents/command')),
                ('filetype', models.CharField(default=None, max_length=50)),
                ('command', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.command')),
            ],
        ),
    ]
