# Generated by Django 4.2 on 2023-05-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingfile',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/documents/training'),
        ),
    ]
