# Generated by Django 4.2 on 2023-06-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
