# Generated by Django 4.2 on 2023-05-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, upload_to='static/documents/leave')),
                ('filetype', models.CharField(default=None, max_length=50)),
                ('leave', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.leave')),
            ],
        ),
    ]
