# Generated by Django 4.2 on 2023-05-28 22:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_remove_curraffiliation_editdate_and_more'),
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='editor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='EditorPerformance', to='baseapp.personnel'),
        ),
        migrations.AddField(
            model_name='performance',
            name='editorDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performance',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderPerformance', to='baseapp.personnel'),
        ),
    ]
