# Generated by Django 4.2 on 2023-05-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0002_leavefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavefile',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/documents/leave'),
        ),
        migrations.CreateModel(
            name='LeaveURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default=None, max_length=255)),
                ('leave', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workapp.leave')),
            ],
        ),
    ]
