# Generated by Django 4.2 on 2023-05-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0002_alter_trainingfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='eduSemeter',
            field=models.IntegerField(default=0),
        ),
    ]
