# Generated by Django 4.2 on 2023-05-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0002_performance_editor_performance_editordate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='editorDate',
            new_name='editDate',
        ),
        migrations.AddField(
            model_name='researchperson',
            name='percent',
            field=models.IntegerField(default=100),
        ),
    ]
