# Generated by Django 4.2 on 2023-05-25 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_permission'),
        ('workapp', '0003_alter_command_edusemeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandperson',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderCommandPerson', to='baseapp.personnel'),
        ),
        migrations.AlterField(
            model_name='commandperson',
            name='personnel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PersonnelCommandPerson', to='baseapp.personnel'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='personnel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='CommandPersonnelLeave', to='baseapp.personnel'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='CommandRecorderLeave', to='baseapp.personnel'),
        ),
    ]
