# Generated by Django 4.2 on 2023-06-07 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0003_rename_editordate_performance_editdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='percent_resp',
        ),
    ]
