# Generated by Django 4.2 on 2023-07-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0003_rename_percent_success_research_percentsuccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='publishDb',
            field=models.TextField(default='N/A'),
        ),
    ]
