# Generated by Django 4.2 on 2023-05-27 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_personnel_options'),
        ('workapp', '0004_commandperson_recorder_alter_commandperson_personnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandfile',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderCommandFile', to='baseapp.personnel'),
        ),
        migrations.AddField(
            model_name='commandurl',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderCommandURL', to='baseapp.personnel'),
        ),
    ]
