# Generated by Django 4.2 on 2023-06-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0004_remove_research_percent_resp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchperson',
            name='status',
            field=models.CharField(default='หัวหน้าโครงการ', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialservice',
            name='topic',
            field=models.TextField(default=''),
        ),
    ]
