# Generated by Django 4.2 on 2023-05-27 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_personnel_options'),
        ('workapp', '0005_commandfile_recorder_commandurl_recorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavefile',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderLeaveFile', to='baseapp.personnel'),
        ),
        migrations.AddField(
            model_name='leaveurl',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderLeaveURL', to='baseapp.personnel'),
        ),
        migrations.AddField(
            model_name='performancefile',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderPerformanceFile', to='baseapp.personnel'),
        ),
        migrations.AddField(
            model_name='performanceurl',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderPerformanceURL', to='baseapp.personnel'),
        ),
        migrations.AddField(
            model_name='researchfile',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderResearchFile', to='baseapp.personnel'),
        ),
        migrations.AddField(
            model_name='researchperson',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderResearchPerson', to='baseapp.personnel'),
        ),
        migrations.AddField(
            model_name='researchurl',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderResearchURL', to='baseapp.personnel'),
        ),
        migrations.AddField(
            model_name='socialservicefile',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderSocialServiceFile', to='baseapp.personnel'),
        ),
        migrations.AddField(
            model_name='socialserviceperson',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderSocialServicePerson', to='baseapp.personnel'),
        ),
        migrations.AddField(
            model_name='socialserviceurl',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderSocialServiceURL', to='baseapp.personnel'),
        ),
        migrations.AddField(
            model_name='trainingfile',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderTrainingFile', to='baseapp.personnel'),
        ),
        migrations.AddField(
            model_name='trainingurl',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderTrainingURL', to='baseapp.personnel'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='personnel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PersonnelLeave', to='baseapp.personnel'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecorderLeave', to='baseapp.personnel'),
        ),
    ]
