# Generated by Django 4.2 on 2023-06-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0005_alter_researchperson_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavefile',
            old_name='editDate',
            new_name='recordDate',
        ),
        migrations.RenameField(
            model_name='leaveurl',
            old_name='editDate',
            new_name='recordDate',
        ),
    ]
