# Generated by Django 4.2 on 2023-05-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0006_leavefile_recorder_leaveurl_recorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='personnel',
            new_name='recorder',
        ),
    ]
