# Generated by Django 4.2 on 2023-06-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0006_rename_editdate_leavefile_recorddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandurl',
            name='description',
            field=models.URLField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='leaveurl',
            name='description',
            field=models.URLField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='performanceurl',
            name='description',
            field=models.URLField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='researchurl',
            name='description',
            field=models.URLField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='socialserviceurl',
            name='description',
            field=models.URLField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='trainingurl',
            name='description',
            field=models.URLField(default=None, max_length=255),
        ),
    ]
