# Generated by Django 4.2 on 2023-06-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0007_commandurl_description_leaveurl_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandurl',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='leaveurl',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceurl',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='researchurl',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='socialserviceurl',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingurl',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
