# Generated by Django 4.2 on 2023-06-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0008_alter_commandurl_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='keyword',
        ),
        migrations.AddField(
            model_name='research',
            name='reference',
            field=models.TextField(default='-'),
        ),
    ]
