# Generated by Django 4.2 on 2023-05-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_personnel_options'),
        ('workapp', '0009_alter_socialserviceperson_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchperson',
            name='personnel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PersonnelResearchPerson', to='baseapp.personnel'),
        ),
    ]
